project_id = "uszlfqgxjvceugrpavde"

[functions.daisycon-auth]
verify_jwt = false

[functions.daisycon-import]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-search-alerts]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.post-to-facebook]
verify_jwt = false

[functions.daily-alert-subscribe]
verify_jwt = false

[functions.daily-alert-unsubscribe]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.admin-reset]
verify_jwt = false
